export const artists = [
    {
        "id": 1,
        "Name": "Dxrk ダーク",
        "Picture": "/assets/artist/dxrk.webp",
        "Bio": "If there’s any artist who can say they had a big year, it’s Dxrk ダーク. Starting 2022 as an unknown entity, the Algerian phonk producer ended the year as the most-streamed artist from the Middle East and North Africa globally. ",
        "Www": "https://album.link/pg2htks8b90nf",
        "InstagramUrl": "https://www.instagram.com/prodbydxrk/",
        "Instagram": "Instagram:",
        "InstagramTag": "@prodbydxrk",
        "TikTokUrl": "https://www.tiktok.com/@prodbydxrk",
        "TikTok": "TikTok:",
        "TikTokTag": "prodbydxrk",
        "TwitterUrl": "https://twitter.com/prodbydxrk",
        "Twitter": "Twitter:",
        "TwitterTag": "@prodbydxrk",
        "FacebookUrl": "https://www.facebook.com/itsdxxrk/",
        "Facebook": "Facebook:",
        "FacebookTag": "Dxrk ダーク",
        "YouTubeUrl": "https://www.youtube.com/@prodbydxrk",
        "YouTube": "Youtube:",
        "YouTubeTag": "@prodbydxrk",
    },
    {
        "id": 2,
        "Name": "Mishashi Sensei",
        "Picture": "/assets/artist/mishasisensei.webp",
        "Bio": "Hi Sensei is here I make music in phonk style and not only listen to the new release and thank you all for listening to me, thanks a lot. for those who don't know anything about me, you can go to my IG and no, this is not a brilliant plan to replenish IG and Hi Mom IG: @mishashi_sensei YT: https://www.youtube.com/c/MishashiSensei ArtistLink: https://linktr.ee/mishashi_sensei",
        "Www": "https://linktr.ee/mishashi_sensei",
        "InstagramUrl": "https://www.instagram.com/mishashi_sensei/",
        "Instagram": "Instagram:",
        "InstagramTag": "@mishashi_sensei",
        "TikTokUrl": "https://www.tiktok.com/@mishashisensei",
        "TikTok": "TikTok:",
        "TikTokTag": "@mishashisensei",
        "TwitterUrl": "",
        "Twitter": "",
        "TwitterTag": "",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/channel/UCa-hPVaPIUVBaJjwYEH4Tsg",
        "YouTube": "Youtube:",
        "YouTubeTag": "@MishashiSensei",
    },
    {
        "id": 3,
        "Name": "isolate.exe",
        "Picture": "/assets/artist/isolate.webp",
        "Bio": "Oops. Looks like we don't have the bio of this artist yet. Try again later.",
        "Www": "",
        "InstagramUrl": "https://www.instagram.com/isolate_exe/",
        "Instagram": "Instagram:",
        "InstagramTag": "@isolate_exe",
        "TikTokUrl": "https://www.tiktok.com/@isolate.exe",
        "TikTok": "TikTok:",
        "TikTokTag": "@isolate.exe",
        "TwitterUrl": "",
        "Twitter": "",
        "TwitterTag": "",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/channel/UCWOq1KsIzmDrROUv19Lzn0g",
        "YouTube": "Youtube:",
        "YouTubeTag": "@isolateexe",
    },
    {
        "id": 4,
        "Name": "PLAYAMANE",
        "Picture": "/assets/artist/playmane.webp",
        "Bio": "Oops. Looks like we don't have the bio of this artist yet. Try again later.",
        "Www": "https://linktr.ee/playamane",
        "InstagramUrl": "https://www.instagram.com/playamxne/",
        "Instagram": "Instagram:",
        "InstagramTag": "@playamxne",
        "TikTokUrl": "https://www.tiktok.com/@playamane1337",
        "TikTok": "TikTok:",
        "TikTokTag": "@playamane1337",
        "TwitterUrl": "",
        "Twitter": "",
        "TwitterTag": "",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/channel/UCnX0-P-d5yz_x_w4-y-pOxA",
        "YouTube": "YouTube:",
        "YouTubeTag": "@PLAYAMXNE",
    },
    {
        "id": 5,
        "Name": "Skorde",
        "Picture": "/assets/artist/skorde.webp",
        "Bio": "Im Skorde also known as SPURME. Biggest Phonk artist in Finland.",
        "Www": "https://distrokid.com/hyperfollow/skorde/devilspeed",
        "InstagramUrl": "",
        "Instagram": "",
        "InstagramTag": "",
        "TikTokUrl": "",
        "TikTok": "",
        "TikTokTag": "",
        "TwitterUrl": "https://twitter.com/SPURMEWasTaken",
        "Twitter": "Twitter:",
        "TwitterTag": "@SPURMEWasTaken",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/channel/UCbGQq-G26T5xTeUK-V7qfRw",
        "YouTube": "Youtube:",
        "YouTubeTag": "@skorde_",
    },
    {
        "id": 6,
        "Name": "MUPP",
        "Picture": "/assets/artist/mupp.webp",
        "Bio": "Oops. Looks like we don't have the bio of this artist yet. Try again later.",
        "Www": "https://t.me/muppbroken",
        "InstagramUrl": "https://www.instagram.com/muppbroken/",
        "Instagram": "Instagram:",
        "InstagramTag": "@muppbroken",
        "TikTokUrl": "",
        "TikTok": "",
        "TikTokTag": "",
        "TwitterUrl": "",
        "Twitter": "",
        "TwitterTag": "",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/channel/UCWM6eXRMaCSyOSzFvm7Xodw",
        "YouTube": "Youtube:",
        "YouTubeTag": "@MUPPBROKENYOURHEART",
    },
    {
        "id": 7,
        "Name": "PRXSXNT FXTURE",
        "Picture": "/assets/artist/prxsxntfxture.webp",
        "Bio": "Moscow, Russian Federation. I prefer the future house style or remixing .at worst I do everything.",
        "Www": "",
        "InstagramUrl": "",
        "Instagram": "",
        "InstagramTag": "",
        "TikTokUrl": "",
        "TikTok": "",
        "TikTokTag": "",
        "TwitterUrl": "",
        "Twitter": "",
        "TwitterTag": "",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/channel/UC2j0Pf47ehU4gvEGtc4D1Qg",
        "YouTube": "Youtube:",
        "YouTubeTag": "@prxsxntfxture",
    },
    {
        "id": 8,
        "Name": "PlayaPhonk",
        "Picture": "/assets/artist/playphonk.webp",
        "Bio": "Oops. Looks like we don't have the bio of this artist yet. Try again later.",
        "Www": "https://playaphonk.lnk.to/REALMTOPARADISE",
        "InstagramUrl": "https://www.instagram.com/officialplayaphonk",
        "Instagram": "Instagram:",
        "InstagramTag": "@officialplayaphonk",
        "TikTokUrl": "",
        "TikTok": "",
        "TikTokTag": "",
        "TwitterUrl": "https://twitter.com/d00mshop",
        "Twitter": "Twitter:",
        "TwitterTag": "@D00MSHOP",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/@playaphonkvevo1374",
        "YouTube": "Youtube:",
        "YouTubeTag": "@PlayaPhonkOfficial",
    },
    {
        "id": 9,
        "Name": "Yavomag",
        "Picture": "/assets/artist/yavomag.webp",
        "Bio": "Producer and rapper. The Yavomag phonk project began in 2020 inspired by $uicideboy$ and harmacist. tarted off with a jdm tiktok hit Phonk666 , and now have created a lot of singles and collaborations, including big artists like Sinizter and Luga. Besides Phonk, Yavomag is a rapper, way longer than phonk production and will be releasing some time in 2023. Additionally Yavomag has been producing other genres like Witchouse; an EP Witch & Plague with fellow producer RVRE . Yavomag has also helped launch phonk careers for Bozubuck, Falxce, Boodamane, GHO6TBXSTA and Yavomag’s own brother DeadJxhn. Apart from artists, Yavomag has grown a song art cover designer to be come a top seller. (IG: Phonk.art)",
        "Www": "https://distrokid.com/hyperfollow/yavomagandrubikdiceandchilx/legend-of-oni-i",
        "InstagramUrl": "https://www.instagram.com/yavomag_hiphop",
        "Instagram": "Instagram:",
        "InstagramTag": "@yavomag_hiphop",
        "TikTokUrl": "",
        "TikTok": "",
        "TikTokTag": "",
        "TwitterUrl": "",
        "Twitter": "",
        "TwitterTag": "",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/channel/UClh-Ba70AwGanDyColuzrCg",
        "YouTube": "Youtube:",
        "YouTubeTag": "@yavomag7712",
    },
    {
        "id": 10,
        "Name": "kaizx",
        "Picture": "/assets/artist/kaizx.webp",
        "Bio": "",
        "Www": "https://discord.com/invite/NSVPZnqhCu",
        "InstagramUrl": "https://www.instagram.com/insolentecorde",
        "Instagram": "Instagram:",
        "InstagramTag": "@insolentecorde",
        "TikTokUrl": "",
        "TikTok": "",
        "TikTokTag": "",
        "TwitterUrl": "",
        "Twitter": "",
        "TwitterTag": "",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "",
        "YouTube": "",
        "YouTubeTag": "",
    }
]