export const artists = [
    {
        "id": 1,
        "Name": "Dxrk ダーク",
        "Picture": "/assets/artist/dxrk.jpg",
        "Bio": "If there’s any artist who can say they had a big year, it’s Dxrk ダーク. Starting 2022 as an unknown entity, the Algerian phonk producer ended the year as the most-streamed artist from the Middle East and North Africa globally. ",
        "Www": "https://album.link/pg2htks8b90nf",        
        "InstagramUrl": "https://www.instagram.com/prodbydxrk/",
        "Instagram": "Instagram:",
        "InstagramTag": "@prodbydxrk",
        "TikTokUrl": "https://www.tiktok.com/@prodbydxrk",
        "TikTok": "TikTok:",
        "TikTokTag": "prodbydxrk",
        "TwitterUrl": "https://twitter.com/prodbydxrk",
        "Twitter": "Twitter:",
        "TwitterTag": "@prodbydxrk",
        "FacebookUrl": "https://www.facebook.com/itsdxxrk/",
        "Facebook": "Facebook:",        
        "FacebookTag": "Dxrk ダーク",
        "YouTubeUrl": "https://www.youtube.com/@prodbydxrk",
        "YouTube": "Youtube:",
        "YouTubeTag": "Dxrk ダーク ",
    },
    {
        "id": 2,
        "Name": "Mishashi Sensei",
        "Picture": "/assets/artist/mishasisensei.jpg",
        "Www": "",
        "WwwUrl": "",
        "SpotifyUrl": "",
        "Spotify": "",
        "SounCloudUrl": "",
        "SounCloud": "",
        "AppleMusicUrl": "",
        "AppleMusic": "",
        "YoutubeUrl": "",
        "Youtube": "",
        "InstagramUrl": "",
        "Instagram": "",
        "TikTokUrl": "",
        "TikTok": "",
        "TwitterUrl": "",
        "Twitter": "",
        "FacebookUrl": "",
        "Facebook": "",
    },
    {
        "id": 3,
        "Name": "isolate.exe",
        "Picture": "/assets/artist/isolate.jpg",
        "Www": "",
        "WwwUrl": "",
        "SpotifyUrl": "",
        "Spotify": "",
        "SounCloudUrl": "",
        "SounCloud": "",
        "AppleMusicUrl": "",
        "AppleMusic": "",
        "YoutubeUrl": "",
        "Youtube": "",
        "InstagramUrl": "",
        "Instagram": "",
        "TikTokUrl": "",
        "TikTok": "",
        "TwitterUrl": "",
        "Twitter": "",
        "FacebookUrl": "",
        "Facebook": "",
    },
    {
        "id": 4,
        "Name": "PLAYAMANE",
        "Picture": "/assets/artist/playmane.jpg",
        "Www": "",
        "WwwUrl": "",
        "SpotifyUrl": "",
        "Spotify": "",
        "SounCloudUrl": "",
        "SounCloud": "",
        "AppleMusicUrl": "",
        "AppleMusic": "",
        "YoutubeUrl": "",
        "Youtube": "",
        "InstagramUrl": "",
        "Instagram": "",
        "TikTokUrl": "",
        "TikTok": "",
        "TwitterUrl": "",
        "Twitter": "",
        "FacebookUrl": "",
        "Facebook": "",
    },
    {
        "id": 5,
        "Name": "Skorde",
        "Picture": "/assets/artist/skorde.jpg",
        "Www": "",
        "WwwUrl": "",
        "SpotifyUrl": "",
        "Spotify": "",
        "SounCloudUrl": "",
        "SounCloud": "",
        "AppleMusicUrl": "",
        "AppleMusic": "",
        "YoutubeUrl": "",
        "Youtube": "",
        "InstagramUrl": "",
        "Instagram": "",
        "TikTokUrl": "",
        "TikTok": "",
        "TwitterUrl": "",
        "Twitter": "",
        "FacebookUrl": "",
        "Facebook": "",
    },
    {
        "id": 6,
        "Name": "MUPP",
        "Picture": "/assets/artist/mupp.jpg",
        "Www": "",
        "WwwUrl": "",
        "SpotifyUrl": "",
        "Spotify": "",
        "SounCloudUrl": "",
        "SounCloud": "",
        "AppleMusicUrl": "",
        "AppleMusic": "",
        "YoutubeUrl": "",
        "Youtube": "",
        "InstagramUrl": "",
        "Instagram": "",
        "TikTokUrl": "",
        "TikTok": "",
        "TwitterUrl": "",
        "Twitter": "",
        "FacebookUrl": "",
        "Facebook": "",
    },
    {
        "id": 7,
        "Name": "PRXSXNT FXTURE",
        "Picture": "/assets/artist/prxsxntfxture.jpg",
        "Www": "",
        "WwwUrl": "",
        "SpotifyUrl": "",
        "Spotify": "",
        "SounCloudUrl": "",
        "SounCloud": "",
        "AppleMusicUrl": "",
        "AppleMusic": "",
        "YoutubeUrl": "",
        "Youtube": "",
        "InstagramUrl": "",
        "Instagram": "",
        "TikTokUrl": "",
        "TikTok": "",
        "TwitterUrl": "",
        "Twitter": "",
        "FacebookUrl": "",
        "Facebook": "",
    },
    {
        "id": 8,
        "Name": "PlayaPhonk",
        "Picture": "/assets/artist/playphonk.jpg",
        "Www": "",
        "WwwUrl": "",
        "SpotifyUrl": "",
        "Spotify": "",
        "SounCloudUrl": "",
        "SounCloud": "",
        "AppleMusicUrl": "",
        "AppleMusic": "",
        "YoutubeUrl": "",
        "Youtube": "",
        "InstagramUrl": "",
        "Instagram": "",
        "TikTokUrl": "",
        "TikTok": "",
        "TwitterUrl": "",
        "Twitter": "",
        "FacebookUrl": "",
        "Facebook": "",
    },
    {
        "id": 9,
        "Name": "Yavomag",
        "Picture": "/assets/artist/yavomag.jpg",
        "Www": "",
        "WwwUrl": "",
        "SpotifyUrl": "",
        "Spotify": "",
        "SounCloudUrl": "",
        "SounCloud": "",
        "AppleMusicUrl": "",
        "AppleMusic": "",
        "YoutubeUrl": "",
        "Youtube": "",
        "InstagramUrl": "",
        "Instagram": "",
        "TikTokUrl": "",
        "TikTok": "",
        "TwitterUrl": "",
        "Twitter": "",
        "FacebookUrl": "",
        "Facebook": "",
    },

]