export const artists = [
    {
        "id": 1,
        "Name": "Dxrk ダーク",
        "Picture": "/assets/artist/dxrk.webp",
        "Bio": "ダーク, has, virtually overnight, captured the eyes and ears of the entire phonk community with his TikTok viral smash, RAVE. Despite his current EDM heavy direction, growing up, Tahar found inspiration in the early SoundCloud rap era, listening to guys like Comenthazine and Smokepurpp. Similar to much of the Phonk production community, his leap from standard Rap to Phonk was influenced almost solely by $uicideboys back in 2015. From there, his production style expanded as Phonk evolved into the dance centric sound we hear today, and thus RAVE was born. With Phonk's meteoric rise into 2022, Dxrk ダーク now holds a top three position in one of the fastest growing underground musical cultures. Riding on the coattails of his still very fresh hit, Dxrk ダーク is gearing up for a heavy release load up and throughout the Summer, 2022.",
        "Www": "https://album.link/pg2htks8b90nf",
        "InstagramUrl": "https://www.instagram.com/prodbydxrk/",
        "Instagram": "Instagram:",
        "InstagramTag": "@prodbydxrk",
        "TikTokUrl": "https://www.tiktok.com/@prodbydxrk",
        "TikTok": "TikTok:",
        "TikTokTag": "prodbydxrk",
        "TwitterUrl": "https://twitter.com/prodbydxrk",
        "Twitter": "Twitter:",
        "TwitterTag": "@prodbydxrk",
        "FacebookUrl": "https://www.facebook.com/itsdxxrk/",
        "Facebook": "Facebook:",
        "FacebookTag": "Dxrk ダーク",
        "YouTubeUrl": "https://www.youtube.com/@prodbydxrk",
        "YouTube": "Youtube:",
        "YouTubeTag": "@prodbydxrk",
    },
    {
        "id": 2,
        "Name": "Mishashi Sensei",
        "Picture": "/assets/artist/mishasisensei.webp",
        "Bio": "Hi Sensei is here I make music in phonk style and not only listen to the new release and thank you all for listening to me, thanks a lot. for those who don't know anything about me, you can go to my IG and no, this is not a brilliant plan to replenish IG and Hi Mom IG: @mishashi_sensei YT: https://www.youtube.com/c/MishashiSensei ArtistLink: https://linktr.ee/mishashi_sensei",
        "Www": "https://linktr.ee/mishashi_sensei",
        "InstagramUrl": "https://www.instagram.com/mishashi_sensei/",
        "Instagram": "Instagram:",
        "InstagramTag": "@mishashi_sensei",
        "TikTokUrl": "https://www.tiktok.com/@mishashisensei",
        "TikTok": "TikTok:",
        "TikTokTag": "@mishashisensei",
        "TwitterUrl": "",
        "Twitter": "",
        "TwitterTag": "",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/channel/UCa-hPVaPIUVBaJjwYEH4Tsg",
        "YouTube": "Youtube:",
        "YouTubeTag": "@MishashiSensei",
    },
    {
        "id": 3,
        "Name": "isolate.exe",
        "Picture": "/assets/artist/isolate.webp",
        "Bio": "Isolate is a renowned musical artist who started posting their music since January 28, 2022. In a short period of time, they have already amassed over 50 million views on YouTube. Their unique and captivating musical style has garnered attention from a wide audience, leading to rapid popularity. With their artistic creativity and exceptional musical talents, Isolate has managed to stand out in the contemporary music industry. Their songs are appreciated for their catchy melodies, profound lyrics, and high-quality production. Isolate continues to win the hearts of their fans through hard work, passion, and dedication to the art of music.",
        "Www": "",
        "InstagramUrl": "https://www.instagram.com/isolate_exe/",
        "Instagram": "Instagram:",
        "InstagramTag": "@isolate_exe",
        "TikTokUrl": "https://www.tiktok.com/@isolate.exe",
        "TikTok": "TikTok:",
        "TikTokTag": "@isolate.exe",
        "TwitterUrl": "",
        "Twitter": "",
        "TwitterTag": "",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/channel/UCWOq1KsIzmDrROUv19Lzn0g",
        "YouTube": "Youtube:",
        "YouTubeTag": "@isolateexe",
    },
    {
        "id": 4,
        "Name": "PLAYAMANE",
        "Picture": "/assets/artist/playmane.webp",
        "Bio": "Playamane is a phonk producer hailing from Argentina, known for accumulating over 100 million Spotify streams. With their distinct style and innovative approach to music production, Playamane has garnered a significant following and recognition on the streaming platform. Their tracks have resonated with listeners around the world, showcasing their talent and ability to create captivating and infectious phonk music. As an artist, Playamane continues to make waves in the industry, pushing boundaries and leaving a lasting impact on the global music scene.",
        "Www": "https://linktr.ee/playamane",
        "InstagramUrl": "https://www.instagram.com/playamxne/",
        "Instagram": "Instagram:",
        "InstagramTag": "@playamxne",
        "TikTokUrl": "https://www.tiktok.com/@playamane1337",
        "TikTok": "TikTok:",
        "TikTokTag": "@playamane1337",
        "TwitterUrl": "",
        "Twitter": "",
        "TwitterTag": "",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/channel/UCnX0-P-d5yz_x_w4-y-pOxA",
        "YouTube": "YouTube:",
        "YouTubeTag": "@PLAYAMXNE",
    },
    {
        "id": 5,
        "Name": "Skorde",
        "Picture": "/assets/artist/skorde.webp",
        "Bio": "Skorde, also known as SPURME, is a Finnish artist who has been sharing their unique funk music since 2014. Despite having a modest view count of over 7 million, their style is absolutely sublime and will have you coming back for more. Skorde's music has a captivating quality that will make you want to rediscover their songs time and time again. Their talent and artistry shine through each composition, creating a truly immersive and enjoyable experience for listeners. Keep an ear out for Skorde's captivating funk creations as they continue to showcase their musical prowess.",
        "Www": "https://distrokid.com/hyperfollow/skorde/devilspeed",
        "InstagramUrl": "",
        "Instagram": "",
        "InstagramTag": "",
        "TikTokUrl": "",
        "TikTok": "",
        "TikTokTag": "",
        "TwitterUrl": "https://twitter.com/SPURMEWasTaken",
        "Twitter": "Twitter:",
        "TwitterTag": "@SPURMEWasTaken",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/channel/UCbGQq-G26T5xTeUK-V7qfRw",
        "YouTube": "Youtube:",
        "YouTubeTag": "@skorde_",
    },
    {
        "id": 6,
        "Name": "MUPP",
        "Picture": "/assets/artist/mupp.webp",
        "Bio": "MUPP, this up-and-coming artist, has been making waves in the music scene since March 2016. With over 47 million views, it's clear that quantity aligns perfectly with quality when it comes to their work. MUPP's mesmerizing performances and exceptional talent have captivated a wide audience, solidifying their place in the music industry. Each view serves as a testament to the remarkable artistry and dedication that MUPP brings to their craft. Prepare to be enthralled as MUPP continues to deliver outstanding music that resonates with fans worldwide.",
        "Www": "https://t.me/muppbroken",
        "InstagramUrl": "https://www.instagram.com/muppbroken/",
        "Instagram": "Instagram:",
        "InstagramTag": "@muppbroken",
        "TikTokUrl": "",
        "TikTok": "",
        "TikTokTag": "",
        "TwitterUrl": "",
        "Twitter": "",
        "TwitterTag": "",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/channel/UCWM6eXRMaCSyOSzFvm7Xodw",
        "YouTube": "Youtube:",
        "YouTubeTag": "@MUPPBROKENYOURHEART",
    },
    {
        "id": 7,
        "Name": "PRXSXNT FXTURE",
        "Picture": "/assets/artist/prxsxntfxture.webp",
        "Bio": "PRXSXNT FXTURE is a Russian artist in the music industry since January 2021. With their atypical style, they have amassed 34 million views and they're not done showing you what they're capable of. Their music is bound to captivate you, making subscribing to their channel feel like pressing a red button that you'll frantically press. Get ready for an exciting musical journey as PRXSXNT FXTURE continues to push boundaries and deliver their unique sound to their dedicated fan base.",
        "Www": "",
        "InstagramUrl": "",
        "Instagram": "",
        "InstagramTag": "",
        "TikTokUrl": "",
        "TikTok": "",
        "TikTokTag": "",
        "TwitterUrl": "",
        "Twitter": "",
        "TwitterTag": "",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/channel/UC2j0Pf47ehU4gvEGtc4D1Qg",
        "YouTube": "Youtube:",
        "YouTubeTag": "@prxsxntfxture",
    },
    {
        "id": 8,
        "Name": "PlayaPhonk",
        "Picture": "/assets/artist/playphonk.webp",
        "Bio": "Playaphonk is a musical artist who has been posting music since September 2021. Despite starting during the COVID pandemic, they have managed to accumulate over 8 million views. However, don't be mistaken – Playaphonk is a talented artist who releases rare gems. Their music stands out with its unique style and exceptional quality. Playaphonk's artistry and talent shine through in every piece they create, captivating listeners with their distinct sound. Their ability to create musical masterpieces sets them apart from the crowd, and they continue to impress audiences with their creativity and skill. Keep an eye on Playaphonk as they continue to deliver exceptional music that is truly one-of-a-kind.",
        "Www": "https://playaphonk.lnk.to/REALMTOPARADISE",
        "InstagramUrl": "https://www.instagram.com/officialplayaphonk",
        "Instagram": "Instagram:",
        "InstagramTag": "@officialplayaphonk",
        "TikTokUrl": "",
        "TikTok": "",
        "TikTokTag": "",
        "TwitterUrl": "https://twitter.com/d00mshop",
        "Twitter": "Twitter:",
        "TwitterTag": "@D00MSHOP",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/@playaphonkvevo1374",
        "YouTube": "Youtube:",
        "YouTubeTag": "@PlayaPhonkOfficial",
    },
    {
        "id": 9,
        "Name": "Yavomag",
        "Picture": "/assets/artist/yavomag.webp",
        "Bio": "Producer and rapper. The Yavomag phonk project began in 2020 inspired by $uicideboy$ and harmacist. tarted off with a jdm tiktok hit Phonk666 , and now have created a lot of singles and collaborations, including big artists like Sinizter and Luga. Besides Phonk, Yavomag is a rapper, way longer than phonk production and will be releasing some time in 2023. Additionally Yavomag has been producing other genres like Witchouse; an EP Witch & Plague with fellow producer RVRE . Yavomag has also helped launch phonk careers for Bozubuck, Falxce, Boodamane, GHO6TBXSTA and Yavomag’s own brother DeadJxhn. Apart from artists, Yavomag has grown a song art cover designer to be come a top seller. (IG: Phonk.art)",
        "Www": "https://distrokid.com/hyperfollow/yavomagandrubikdiceandchilx/legend-of-oni-i",
        "InstagramUrl": "https://www.instagram.com/yavomag_hiphop",
        "Instagram": "Instagram:",
        "InstagramTag": "@yavomag_hiphop",
        "TikTokUrl": "",
        "TikTok": "",
        "TikTokTag": "",
        "TwitterUrl": "",
        "Twitter": "",
        "TwitterTag": "",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "https://www.youtube.com/channel/UClh-Ba70AwGanDyColuzrCg",
        "YouTube": "Youtube:",
        "YouTubeTag": "@yavomag7712",
    },
    {
        "id": 10,
        "Name": "kaizx",
        "Picture": "/assets/artist/kaizx.webp",
        "Bio": "Oops. Looks like we don't have the bio of this artist yet. Try again later.",
        "Www": "https://discord.com/invite/NSVPZnqhCu",
        "InstagramUrl": "https://www.instagram.com/insolentecorde",
        "Instagram": "Instagram:",
        "InstagramTag": "@insolentecorde",
        "TikTokUrl": "",
        "TikTok": "",
        "TikTokTag": "",
        "TwitterUrl": "",
        "Twitter": "",
        "TwitterTag": "",
        "FacebookUrl": "",
        "Facebook": "",
        "FacebookTag": "",
        "YouTubeUrl": "",
        "YouTube": "",
        "YouTubeTag": "",
    }
]