export const events = [
    
    {
        "id": 1,
        "Name": "THE initial MEETING",        
        "Picture": "/assets/event/theinitialmeetingcover.webp",
        "Where": "Avenue de Miramar, 1020 Bruxelles",
        "When": "June 18",
        "Price": "Free",
        "id1": "",
        "Id1": 1,
        "id2": "Mishashi Sensei",
        "Id2": 2,
        "id3": "",
        "Id3": 3,
        "id4": "PLAYAMANE",
        "Id4": 4,
        "id5": "",
        "Id5": 5,
        "id6": "MUPP",
        "Id6": 6,
        "id7": "",
        "Id7": 7,
        "id8": "PlayaPhonk",
        "Id8": 8,
        "id9": "Yavomag",
        "Id9": 9,
        "id10": "",
        "Id10": 10,
        "id11": "",    
        "Id11": 11,    
    },
    {
        "id": 2,
        "Name": "rave friday",        
        "Picture": "/assets/event/ravefridaycover.webp",
        "Where": "Avenue Victor Rousseau 208, 1190 Forest",
        "When": " June 30",
        "Price": "Free",
        "id1": "kaizx",
        "Id1": 10,
        "id2": "Mishashi Sensei",
        "Id2": 2,
        "id3": "",
        "Id3": 3,
        "id4": "PLAYAMANE",
        "Id4": 4,
        "id5": "",
        "Id5": 5,
        "id6": "MUPP",
        "Id6": 6,
        "id7": "PRXSXNT FXTURE",
        "Id7": 7,
        "id8": "PlayaPhonk",
        "Id8": 8,
        "id9": "Yavomag",
        "Id9": 9,
        "id10": "",
        "Id10": 10,
        "id11": "",    
        "Id11": 11,
    },  
    {
        "id": 3,
        "Name": "street race",        
        "Picture": "/assets/event/streetracecover.webp",
        "Where": "Rue du Belvédère 27, 1050 Ixelles",
        "When": " July 7",
        "Price": "Free",
        "id1": "",
        "Id1": 1,
        "id2": "Mishashi Sensei",
        "Id2": 2,
        "id3": "",
        "Id3": 3,
        "id4": "PLAYAMANE",
        "Id4": 4,
        "id5": "",
        "Id5": 5,
        "id6": "MUPP",
        "Id6": 6,
        "id7": "",
        "Id7": 7,
        "id8": "PlayaPhonk",
        "Id8": 8,
        "id9": "Yavomag",
        "Id9": 9,
        "id10": "",
        "Id10": 10,
        "id11": "",    
        "Id11": 11,    
    },
    {
        "id": 4,
        "Name": "the PHONK night",        
        "Picture": "/assets/event/phonksidecover.webp",
        "Where": "Avenue de Marathon 135, 1020 Bruxelles",
        "When": "July 14",
        "Price": "5€",
        "id1": "Dxrk ダーク",
        "Id1": 1,
        "id2": "Mishashi Sensei",
        "Id2": 2,
        "id3": "isolate.exe",
        "Id3": 3,
        "id4": "PLAYAMANE",
        "Id4": 4,
        "id5": "Skorde",
        "Id5": 5,
        "id6": "MUPP",
        "Id6": 6,
        "id7": "PRXSXNT FXTURE",
        "Id7": 7,
        "id8": "PlayaPhonk",
        "Id8": 8,
        "id9": "Yavomag",
        "Id9": 9,
        "id10": "",
        "Id10": 10,
        "id11": "",    
        "Id11": 11,   
    }
]