export const events = [
    
    {
        "id": 1,
        "Name": "Phonk List",        
        "Picture": "/assets/event/2.png",
        "Where": "Place de la monnais 18, 1000 Bruxelles",
        "When": " September 28th 2023",
        "id1": "Dxrk ダーク",
        "Id1": 1,
        "id2": "Mishashi Sensei",
        "Id2": 2,
        "id3": "isolate.exe",
        "Id3": 3,
        "id4": "PLAYAMANE",
        "Id4": 4,
        "id5": "Skorde",
        "Id5": 5,
        "id6": "MUPP",
        "Id6": 6,
        "id7": "PRXSXNT FXTURE",
        "Id7": 7,
        "id8": "PlayaPhonk",
        "Id8": 8,
        "id9": "Yavomag",
        "Id9": 9,
        "id10": "",
        "Id10": 10,
        "id11": "",    
        "Id11": 11,
    },
    {
        "id": 2,
        "Name": "Phxrside",        
        "Picture": "/assets/event/3.png",
        "Where": "Place de la monnais 18, 1000 Bruxelles",
        "When": " September 28th 2023",
        "id1": "",
        "Id1": 1,
        "id2": "Mishashi Sensei",
        "Id2": 2,
        "id3": "",
        "Id3": 3,
        "id4": "PLAYAMANE",
        "Id4": 4,
        "id5": "",
        "Id5": 5,
        "id6": "MUPP",
        "Id6": 6,
        "id7": "",
        "Id7": 7,
        "id8": "PlayaPhonk",
        "Id8": 8,
        "id9": "Yavomag",
        "Id9": 9,
        "id10": "",
        "Id10": 10,
        "id11": "",    
        "Id11": 11,    
    }
]