export const events = [
    
    {
        "id": 1,
        "Name": "Phonk List",        
        "Picture": "/assets/event/2.png",
        "Where": "Place de la monnais 18, 1000 Bruxelles",
        "When": " September 28th 2023",
        "id1": "Dxrk ダーク",
        "id2": "dqsv",
        "id3": "Mishashi Sensei",
        "id4": "MUPP",
        "id5": "Yavomag",
        "id6": "PRXSXNT FXTURE",
        "id7": "PlayaPhonk",
        "id8": "",
        "id9": "",
        "id10": "",
        "id11": "",    
    },
    {
        "id": 2,
        "Name": "Phxrside",        
        "Picture": "/assets/event/3.png",
        "Where": "Place de la monnais 18, 1000 Bruxelles",
        "When": " September 28th 2023",
        "id1": "MUPP",
        "id2": "PRXSXNT FXTURE",
        "id3": "Mishashi Sensei",
        "id4": "Dxrk ダーク",
        "id5": "Yavomag",
        "id6": "PLAYAMANE",
        "id7": "PlayaPhonk",
        "id8": "isolate.exe",
        "id9": "Skorde",
        "id10": "",
        "id11": "",    
    }
]