export const releases = [
    {
        "id": 1,
        "Title": "RAVE",
        "Artist": "Dxrk ダーク",
        "Picture": "/assets/cover/ravecover.png",
        "Description": "If there’s any artist who can say they had a big year, it’s Dxrk ダーク. Starting 2022 as an unknown entity, the Algerian phonk producer ended the year as the most-streamed artist from the Middle East and North Africa globally. ",        

        "spotifyURL": "https://open.spotify.com/track/1olz3HctPa2yXmSniaCNLN?si=6462ff470d2a4905",
        "Spotify": "Spotify",
        "IconSfy": "h-1 bg-white w-auto rounded-lg",        
        "LinkSfy": "/link.svg",
        
        "SoundCloudURL": "https://soundcloud.com/prodbydxrk/rave?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
        "SoundCloud": "SoundCloud",
        "IconSC": "h-1 bg-white w-auto rounded-lg",        
        "LinkSC": "/link.svg",

        "YouTubeURL": "https://www.youtube.com/watch?v=PTZgxW_3LIQ",
        "YouTube": "YouTube",
        "IconYT": "h-1 bg-white w-auto rounded-lg",        
        "LinkYT": "/link.svg",

        "AppleMusicURL": "https://music.apple.com/us/album/rave-single/1612134731",
        "AppleMusic": "AppleMusic",
        "IconAM": "h-1 bg-white w-auto rounded-lg",        
        "LinkAM": "/link.svg",
    },    
    {
        "id": 2,
        "Title": "IN THE CLUB ",
        "Artist": "Mishashi Sensei",
        "Picture": "/assets/cover/intheclubcover.jpg",
        "Description": "October 22, 2021 © 2021 Mishashi Sensei",        

        "spotifyURL": "https://open.spotify.com/track/7vX0rvoGneCCOJ2QPruNNZ?si=ccae425f43074944",
        "Spotify": "Spotify",
        "IconSfy": "h-1 bg-white w-auto rounded-lg",        
        "LinkSfy": "/link.svg",
        
        "SoundCloudURL": "https://soundcloud.com/mishashi-sensei/in-the-club?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
        "SoundCloud": "SoundCloud",
        "IconSC": "h-1 bg-white w-auto rounded-lg",        
        "LinkSC": "/link.svg",

        "YouTubeURL": "https://youtu.be/B4VCmGDPkYk",
        "YouTube": "YouTube",
        "IconYT": "h-1 bg-white w-auto rounded-lg",        
        "LinkYT": "/link.svg",

        "AppleMusicURL": "",
        "AppleMusic": "",
        "IconAM": "",        
        "LinkAM": "/links.svg",
    },
    {
        "id": 3,
        "Title": "Crystals",
        "Artist": "Isolate.exe",
        "Picture": "/assets/cover/crystalscover.jpg",
        "Description": "January 28, 2022 © 2022 Isolate.exe",        

        "spotifyURL": "https://open.spotify.com/track/2BH3j05ZXWr5PR30sW079d?si=16540510343a4983",
        "Spotify": "Spotify",
        "IconSfy": "h-1 bg-white w-auto rounded-lg",        
        "LinkSfy": "/link.svg",
        
        "SoundCloudURL": "https://soundcloud.com/user-527654690/crystals?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
        "SoundCloud": "SoundCloud",
        "IconSC": "h-1 bg-white w-auto rounded-lg",        
        "LinkSC": "/link.svg",

        "YouTubeURL": "https://youtu.be/Ov6ymmqp27s",
        "YouTube": "YouTube",
        "IconYT": "h-1 bg-white w-auto rounded-lg",        
        "LinkYT": "/link.svg",

        "AppleMusicURL": "https://music.apple.com/us/album/crystals/1607583458?i=1607583464",
        "AppleMusic": "",
        "IconAM": "",        
        "LinkAM": "/link.svg",
    },
    {
        "id": 4,
        "Title": "Nothing Is Holy ",
        "Artist": "PLAYAMANE",
        "Picture": "/assets/cover/nothingisholy.jpg",
        "Description": "January 21, 2022 © 2022 Kordhell",        

        "spotifyURL": "",
        "Spotify": "Spotify",
        "IconSfy": "h-1 bg-white w-auto rounded-lg",        
        "LinkSfy": "/link.svg",
        
        "SoundCloudURL": "",
        "SoundCloud": "SoundCloud",
        "IconSC": "h-1 bg-white w-auto rounded-lg",        
        "LinkSC": "/link.svg",

        "YouTubeURL": "",
        "YouTube": "YouTube",
        "IconYT": "h-1 bg-white w-auto rounded-lg",        
        "LinkYT": "/link.svg",

        "AppleMusicURL": "",
        "AppleMusic": "AppleMusic",
        "IconAM": "h-1 bg-white w-auto rounded-lg",        
        "LinkAM": "/link.svg",
    },
    {
        "id": 5,
        "Title": "Despair",
        "Artist": "Skorde",
        "Picture": "/assets/cover/despair.jpg",
        "Description": "November 18, 2022 © 2022 Mishashi Sensei",        

        "spotifyURL": "",
        "Spotify": "Spotify",
        "IconSfy": "h-1 bg-white w-auto rounded-lg",        
        "LinkSfy": "/link.svg",
        
        "SoundCloudURL": "",
        "SoundCloud": "SoundCloud",
        "IconSC": "h-1 bg-white w-auto rounded-lg",        
        "LinkSC": "/link.svg",

        "YouTubeURL": "",
        "YouTube": "YouTube",
        "IconYT": "h-1 bg-white w-auto rounded-lg",        
        "LinkYT": "/link.svg",

        "AppleMusicURL": "",
        "AppleMusic": "AppleMusic",
        "IconAM": "h-1 bg-white w-auto rounded-lg",        
        "LinkAM": "/link.svg",
    },
    {
        "id": 6,
        "Title": "r34",
        "Artist": "Dxrk ダーク",
        "Picture": "/assets/cover/r34cover.jpg",
        "Description": "November 18, 2022 © 2022 Mishashi Sensei",        

        "spotifyURL": "",
        "Spotify": "Spotify",
        "IconSfy": "h-1 bg-white w-auto rounded-lg",        
        "LinkSfy": "/link.svg",
        
        "SoundCloudURL": "",
        "SoundCloud": "SoundCloud",
        "IconSC": "h-1 bg-white w-auto rounded-lg",        
        "LinkSC": "/link.svg",

        "YouTubeURL": "",
        "YouTube": "YouTube",
        "IconYT": "h-1 bg-white w-auto rounded-lg",        
        "LinkYT": "/link.svg",

        "AppleMusicURL": "",
        "AppleMusic": "AppleMusic",
        "IconAM": "h-1 bg-white w-auto rounded-lg",        
        "LinkAM": "/link.svg",
    },
    {
        "id": 7,
        "Title": "Tokyo Revengers",
        "Artist": "MUPP",
        "Picture": "/assets/cover/tokyorevengerscover.jpg",
        "Description": "May 25, 2021 © 2022 Mishashi Sensei",        

        "spotifyURL": "",
        "Spotify": "Spotify",
        "IconSfy": "h-1 bg-white w-auto rounded-lg",        
        "LinkSfy": "/link.svg",
        
        "SoundCloudURL": "",
        "SoundCloud": "SoundCloud",
        "IconSC": "h-1 bg-white w-auto rounded-lg",        
        "LinkSC": "/link.svg",

        "YouTubeURL": "",
        "YouTube": "YouTube",
        "IconYT": "h-1 bg-white w-auto rounded-lg",        
        "LinkYT": "/link.svg",

        "AppleMusicURL": "",
        "AppleMusic": "AppleMusic",
        "IconAM": "h-1 bg-white w-auto rounded-lg",        
        "LinkAM": "/link.svg",
    },
    {
        "id": 8,
        "Title": "MIDNIGHT",
        "Artist": "PLAYAMANE",
        "Picture": "/assets/cover/midnightcover.jpg",
        "Description": "May 25, 2021 © 2022 Mishashi Sensei",        

        "spotifyURL": "",
        "Spotify": "Spotify",
        "IconSfy": "h-1 bg-white w-auto rounded-lg",        
        "LinkSfy": "/link.svg",
        
        "SoundCloudURL": "",
        "SoundCloud": "SoundCloud",
        "IconSC": "h-1 bg-white w-auto rounded-lg",        
        "LinkSC": "/link.svg",

        "YouTubeURL": "https://youtu.be/JWdXFmy5ga4",
        "YouTube": "YouTube",
        "IconYT": "h-1 bg-white w-auto rounded-lg",        
        "LinkYT": "/link.svg",

        "AppleMusicURL": "",
        "AppleMusic": "AppleMusic",
        "IconAM": "h-1 bg-white w-auto rounded-lg",        
        "LinkAM": "/link.svg",
    },
    {
        "id": 9,
        "Title": "House",
        "Artist": "PRXSXNT FXTURE",
        "Picture": "/assets/cover/housecover.jpg",
        "Description": "May 25, 2021 © 2022 Mishashi Sensei",        

        "spotifyURL": "",
        "Spotify": "Spotify",
        "IconSfy": "h-1 bg-white w-auto rounded-lg",        
        "LinkSfy": "/link.svg",
        
        "SoundCloudURL": "",
        "SoundCloud": "SoundCloud",
        "IconSC": "h-1 bg-white w-auto rounded-lg",        
        "LinkSC": "/link.svg",

        "YouTubeURL": "",
        "YouTube": "YouTube",
        "IconYT": "h-1 bg-white w-auto rounded-lg",        
        "LinkYT": "/link.svg",

        "AppleMusicURL": "",
        "AppleMusic": "AppleMusic",
        "IconAM": "h-1 bg-white w-auto rounded-lg",        
        "LinkAM": "/link.svg",
    },    
    {
        "id": 10,
        "Title": "IMMORTAL",
        "Artist": "PlayaPhonk",
        "Picture": "/assets/cover/immortalcover.jpg",
        "Description": "May 17, 2022 © 2022 PlayaPhonk",        

        "spotifyURL": "",
        "Spotify": "Spotify",
        "IconSfy": "h-1 bg-white w-auto rounded-lg",        
        "LinkSfy": "/link.svg",
        
        "SoundCloudURL": "",
        "SoundCloud": "SoundCloud",
        "IconSC": "h-1 bg-white w-auto rounded-lg",        
        "LinkSC": "/link.svg",

        "YouTubeURL": "https://youtu.be/5BG6o53cJj0",
        "YouTube": "YouTube",
        "IconYT": "h-1 bg-white w-auto rounded-lg",        
        "LinkYT": "/link.svg",

        "AppleMusicURL": "",
        "AppleMusic": "AppleMusic",
        "IconAM": "h-1 bg-white w-auto rounded-lg",        
        "LinkAM": "/link.svg",
    },
    {
        "id": 11,
        "Title": "Tokyo Rain",
        "Artist": "Yavomag",
        "Picture": "/assets/cover/tokyorain.jpg",
        "Description": "May 17, 2022 © 2022 PlayaPhonk",        

        "spotifyURL": "",
        "Spotify": "Spotify",
        "IconSfy": "h-1 bg-white w-auto rounded-lg",        
        "LinkSfy": "/link.svg",
        
        "SoundCloudURL": "",
        "SoundCloud": "SoundCloud",
        "IconSC": "h-1 bg-white w-auto rounded-lg",        
        "LinkSC": "/link.svg",

        "YouTubeURL": "https://youtu.be/5BG6o53cJj0",
        "YouTube": "YouTube",
        "IconYT": "h-1 bg-white w-auto rounded-lg",        
        "LinkYT": "/link.svg",

        "AppleMusicURL": "",
        "AppleMusic": "AppleMusic",
        "IconAM": "h-1 bg-white w-auto rounded-lg",        
        "LinkAM": "/link.svg",
    },

]